CREATE TABLE avis  (
	id INT AUTO_INCREMENT PRIMARY KEY,
    author VARCHAR(255) NOT NULL,
    quote VARCHAR(255) NOT NULL,
    to_validate VARCHAR(1) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS client (
	id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    tel VARCHAR(255) NOT NULL,
    adresse VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS commande (
	id INT AUTO_INCREMENT PRIMARY KEY,
    montant INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	client_id INT REFERENCES client(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS gestion (
	id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(14) NOT NULL,
    password VARCHAR(14) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

